#!/usr/bin/env python3
"""Generate composite odd-polynomial approximation of sign(x) for EvalReLU.

Three stages p1, p2, p3 (odd, normal basis). Each stage is fitted with
Lawson-IRLS (iteratively reweighted least squares -> near-minimax) to sign(x)
on its own input domain; the next stage's domain is the previous output range.
Verifies the composed max error on |x| in [eps, 1] and emits SignCoeffs.h.

Usage: python3 gen_sign_coeffs.py [eps] [deg1] [deg2] [deg3] [input_scale]

input_scale k folds x -> x/k into the stage-1 coefficients: the emitted
composite evaluates sign(x/k), which equals sign(x) but pushes the
power-basis blow-up cliff from |x| = 1 out to |x| = k (headroom against
activations beyond relu_range and noise-inflated ReLU inputs). The effective
transition band becomes |x| < eps * k, so pick eps = band / k.
"""
import os
import sys

import numpy as np

EPS = float(sys.argv[1]) if len(sys.argv) > 1 else 0.05
DEGS = [int(a) for a in sys.argv[2:5]] or [15, 15, 15]
INPUT_SCALE = float(sys.argv[5]) if len(sys.argv) > 5 else 1.0


def fit_odd_minimax(domain_lo, domain_hi, deg, iters=60, grid=4001):
    """Fit odd poly (degree deg) to sign(x)=1 on [lo,hi] (mirror for -x)."""
    x = np.linspace(domain_lo, domain_hi, grid)
    powers = np.arange(1, deg + 1, 2)
    A = x[:, None] ** powers[None, :]
    target = np.ones_like(x)
    w = np.ones_like(x)
    coef = None
    for _ in range(iters):
        Aw = A * w[:, None]
        coef, *_ = np.linalg.lstsq(Aw, target * w, rcond=None)
        err = np.abs(A @ coef - target)
        w *= np.sqrt(err + 1e-12)          # Lawson update
        w /= w.max()
        w = np.maximum(w, 1e-6)
    return powers, coef


def apply_odd(powers, coef, x):
    return sum(c * np.sign(x) * np.abs(x) ** p for p, c in zip(powers, coef))


def stage_range(powers, coef, lo, hi):
    x = np.linspace(lo, hi, 20001)
    y = apply_odd(powers, coef, x)
    return y.min(), y.max()


stages = []
lo, hi = EPS, 1.0
for i, deg in enumerate(DEGS):
    powers, coef = fit_odd_minimax(lo, hi, deg)
    ymin, ymax = stage_range(powers, coef, lo, hi)
    # normalize so the output never exceeds |1| (keeps EvalPoly domain safe)
    scale = max(abs(ymin), abs(ymax), 1.0)
    coef = coef / scale
    ymin, ymax = ymin / scale, ymax / scale
    stages.append((powers, coef))
    print(f"stage{i+1}: deg={deg} domain=[{lo:.5f},{hi:.5f}] "
          f"-> range=[{ymin:.5f},{ymax:.5f}]")
    lo, hi = min(abs(ymin), ymax), 1.0
    lo = max(lo, 1e-4)

# end-to-end check
x = np.linspace(EPS, 1.0, 40001)
y = x.copy()
for powers, coef in stages:
    y = apply_odd(powers, coef, y)
err = np.max(np.abs(y - 1.0))
print(f"composed max |sign error| on [{EPS}, 1]: {err:.6f}")
relu_err = np.max(np.abs(x * (1 - y) / 2))     # error of x*(1+s)/2 vs relu=x
print(f"=> max relu error (normalized units): {relu_err:.6f}")

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "SignCoeffs.h")
with open(out_path, "w") as f:
    f.write("#pragma once\n")
    f.write("// AUTO-GENERATED by gen_sign_coeffs.py — do not edit.\n")
    f.write(f"// eps={EPS}, degrees={DEGS}, input_scale={INPUT_SCALE}, "
            f"composed sign err={err:.6f}, relu err={relu_err:.6f}\n")
    f.write(f"// safe stage-1 input: |x| <= {INPUT_SCALE:g} "
            f"(power-basis cliff beyond)\n")
    f.write("#include <vector>\n\nnamespace cheddar {\n"
            "namespace example_ops {\n\n")
    f.write("inline const std::vector<std::vector<double>> kSignStages = {\n")
    for si, (powers, coef) in enumerate(stages):
        full = np.zeros(int(powers[-1]) + 1)
        for p, c in zip(powers, coef):
            # stage 1 absorbs the input prescale: c_k -> c_k / k^p
            full[p] = c / (INPUT_SCALE ** p) if si == 0 else c
        f.write("    {" + ", ".join(f"{c:.17g}" for c in full) + "},\n")
    f.write("};\n\n}  // namespace example_ops\n}  // namespace cheddar\n")
print(f"wrote {out_path}")
