#!/usr/bin/env python3
"""Generate a HIGH-PRECISION composite sign(x) for EvalReLU — mixed basis.

Why this exists: the 3-stage default (gen_sign_coeffs.py) emits power-basis
coefficients, which is fine at eps=0.025 (max sum|c| ~ 4.5e3). At MPCNN-grade
precision (eps=2^-13, degrees 15/15/27/27) the deg-27 stages explode to
sum|c| ~ 2.8e9 in power basis — partial sums overflow the CKKS message budget
and the whole sign turns to noise (measured 08-04: acc 0.008~0.012 at every
depth/RANGE). Chebyshev basis keeps the same polynomials at O(1) coefficients.

Mixed-basis layout emitted here:
  stage 1   : power basis (small coeffs; handles the [-input_scale, input_scale]
              raw-input domain, where Chebyshev T_k(x) would blow up for |x|>1)
  stages 2+ : Chebyshev basis, fitted DIRECTLY in odd-T_k least squares
              (inputs are previous-stage outputs, normalized into [-1,1])
Requires the EvalReLU stage_chebyshev flags (ExampleOps.h) so EvalPoly is
constructed with chebyshev=true for the marked stages.

Usage: python3 gen_sign_coeffs_hp.py [eps] [deg1 deg2 ...] [input_scale]
Default: eps=2^-13, degrees 15 15 27 27, input_scale 2.0
"""
import os
import sys

import numpy as np
from numpy.polynomial import chebyshev as C

if len(sys.argv) >= 4:
    EPS = float(sys.argv[1])
    DEGS = [int(a) for a in sys.argv[2:-1]]
    INPUT_SCALE = float(sys.argv[-1])
else:
    EPS, DEGS, INPUT_SCALE = 2.0 ** -13, [15, 15, 27, 27], 2.0


def lawson_fit(A, grid_n, iters=60):
    target = np.ones(grid_n)
    w = np.ones(grid_n)
    coef = None
    for _ in range(iters):
        Aw = A * w[:, None]
        coef, *_ = np.linalg.lstsq(Aw, target * w, rcond=None)
        err = np.abs(A @ coef - target)
        w *= np.sqrt(err + 1e-12)
        w /= w.max()
        w = np.maximum(w, 1e-6)
    return coef


def fit_odd_power(lo, hi, deg, grid=4001):
    x = np.linspace(lo, hi, grid)
    powers = np.arange(1, deg + 1, 2)
    coef = lawson_fit(x[:, None] ** powers[None, :], grid)
    full = np.zeros(deg + 1)
    full[powers] = coef
    return full                      # power-basis vector, low degree first


def fit_odd_cheb(lo, hi, deg, grid=4001):
    x = np.linspace(lo, hi, grid)
    idx = np.arange(1, deg + 1, 2)
    V = C.chebvander(x, deg)
    coef = lawson_fit(V[:, idx], grid)
    full = np.zeros(deg + 1)
    full[idx] = coef
    return full                      # Chebyshev-basis vector, low degree first


def apply_stage(full, cheb, x):
    return C.chebval(x, full) if cheb else np.polynomial.polynomial.polyval(x, full)


stages = []                          # (full_coeffs, is_chebyshev)
lo, hi = EPS, 1.0
for i, deg in enumerate(DEGS):
    cheb = i > 0
    full = fit_odd_cheb(lo, hi, deg) if cheb else fit_odd_power(lo, hi, deg)
    xs = np.linspace(lo, hi, 20001)
    y = apply_stage(full, cheb, xs)
    scale = max(abs(y.min()), abs(y.max()), 1.0)   # keep outputs inside [-1,1]
    full = full / scale
    y = y / scale
    stages.append((full, cheb))
    print(f"stage{i+1}: deg={deg} basis={'cheb' if cheb else 'power'} "
          f"domain=[{lo:.6f},{hi:.5f}] -> range=[{y.min():.5f},{y.max():.5f}] "
          f"max|c|={np.abs(full).max():.3g} sum|c|={np.abs(full).sum():.3g}")
    lo = max(min(abs(y.min()), y.max()), 1e-4)
    hi = 1.0

# ---- end-to-end check in the EMITTED convention (what the C++ evaluates) ----
# stage-1 emission folds input_scale k: c_p -> c_p / k^p, i.e. raw input x with
# |x| <= k, transition band |x| < eps*k.
emit1 = stages[0][0].copy()
for p in range(len(emit1)):
    emit1[p] /= INPUT_SCALE ** p

x_raw = np.linspace(EPS * INPUT_SCALE, INPUT_SCALE, 40001)
y = np.polynomial.polynomial.polyval(x_raw, emit1)
for full, cheb in stages[1:]:
    y = apply_stage(full, cheb, y)
err = np.max(np.abs(y - 1.0))
relu_err = np.max(np.abs(x_raw / INPUT_SCALE * (1 - y) / 2))
print(f"composed max |sign error| on [{EPS * INPUT_SCALE:.6f}, {INPUT_SCALE}] "
      f"(raw units): {err:.6f}")
print(f"=> max relu error (normalized units): {relu_err:.6f}")

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "SignCoeffsHP.h")
depths = [int(np.ceil(np.log2(d + 1))) for d in DEGS]
with open(out_path, "w") as f:
    f.write("#pragma once\n")
    f.write("// AUTO-GENERATED by gen_sign_coeffs_hp.py (mixed-basis v2) — do not edit.\n")
    f.write("// MPCNN(Lee et al., ICML'22) α≈13급 정밀도 재현용: SIGN_HP=1 로 baseline 회로에서만 선택.\n")
    f.write(f"// 깊이 {depths}={sum(depths)}레벨(기본 3x15=12) → ReLU당 부트 증가 = 정밀도의 시간 비용 실측.\n")
    f.write(f"// eps={EPS:.6g}, degrees={DEGS}, input_scale={INPUT_SCALE}, "
            f"composed sign err={err:.6f}, relu err={relu_err:.6f}\n")
    f.write("// v2: stage1 = power basis (raw-input domain), stages 2+ = CHEBYSHEV basis\n")
    f.write("//     (v1 power-basis deg27 had sum|c|~2.8e9 -> CKKS message overflow -> acc~0.01).\n")
    f.write("//     kSignStagesHPCheb 를 EvalReLU 의 stage_chebyshev 인자로 넘겨야 한다.\n")
    f.write("#include <vector>\n\nnamespace cheddar {\nnamespace example_ops {\n\n")
    f.write("inline const std::vector<std::vector<double>> kSignStagesHP = {\n")
    for si, (full, cheb) in enumerate(stages):
        emit = emit1 if si == 0 else full
        f.write("    {" + ", ".join(f"{c:.17g}" for c in emit) + "},\n")
    f.write("};\n\n")
    f.write("inline const std::vector<bool> kSignStagesHPCheb = {"
            + ", ".join("true" if cheb else "false" for _, cheb in stages)
            + "};\n\n")
    f.write("}  // namespace example_ops\n}  // namespace cheddar\n")
print(f"wrote {out_path}")
